"""empty message

Revision ID: 59b32a52bd5a
Revises: 
Create Date: 2025-01-21 16:26:34.748211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b32a52bd5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('phone_number_is_private', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('custom_status', sa.String(length=20), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen_is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('bio_is_private', sa.Boolean(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('birthdate_is_private', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_is_private', sa.Boolean(), nullable=False),
    sa.Column('facebook_link', sa.String(length=255), nullable=True),
    sa.Column('discord_id', sa.String(length=255), nullable=True),
    sa.Column('github_link', sa.String(length=255), nullable=True),
    sa.Column('youtube_link', sa.String(length=255), nullable=True),
    sa.Column('website_link', sa.String(length=255), nullable=True),
    sa.Column('allow_friend_requests', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('job_title_is_private', sa.Boolean(), nullable=False),
    sa.Column('friend_id', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('friend_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('friendships',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id_1', sa.String(length=255), nullable=False),
    sa.Column('user_id_2', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id_1', 'user_id_2', name='unique_friendship')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('group_description', sa.Text(), nullable=True),
    sa.Column('group_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('user1_id', sa.String(length=255), nullable=True),
    sa.Column('user2_id', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_message', sa.String(length=1024), nullable=True),
    sa.Column('last_message_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_memberships',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('sender_id', sa.String(length=255), nullable=False),
    sa.Column('receiver_id', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('media_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('group_memberships')
    op.drop_table('conversations')
    op.drop_table('notifications')
    op.drop_table('groups')
    op.drop_table('friendships')
    op.drop_table('users')
    # ### end Alembic commands ###
